### PR TITLE
remove async-trait

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
Nice work @stevefan1999-personal. Can you please address rustfmt so I can get this merged?

**Comment by stevefan1999-personal** [comment]
> Nice work @stevefan1999-personal. Can you please address rustfmt so I can get this merged?

sure

**Review by AhmedSoliman — APPROVED** [review]
🚢

**Comment by AhmedSoliman** [comment]
Build is failing. I need to bump up MSRV to 1.75.

**Pull request merged**
